### ISSUE TITLE
mix_test_interactive executable

### ISSUE THREAD

**Issue by andyl** [randycoulman/mix_test_interactive#126]
I install mix_test_interactive (MTI) on all of my projects.  It's great.  

But when I work on 3rd party projects, I do not install MTI, and suffer inferior tooling.  Sad.

It would be nice if MTI was available as an executable/escript, or global mix task.

That way, MTI could be used on 3rd party projects without having to install a dependency.

**Comment by randycoulman** [comment]
Hey @andyl, thanks for the suggestion. Some time ago, I looked into making MTI a [mix archive](https://hexdocs.pm/mix/Mix.Tasks.Archive.Build.html), but that requires that it have no dependencies. However, it really needs the `file_system` dependency to do its job, so that's not going to work.

I hadn't thought about releasing it as an escript or other executable, though. That might work. It's probably not something I'm going to do on my own, but I'd be happy to consider a PR.

**Comment by andyl** [comment]
I took a crack at this this eve, trying two methods - escript and plain old elixir script.  Failed with both. Couldn't figure out exactly what dependencies were needed.  For reference, find the elixir script below.  This seems like it ought to work!  Maybe someone else can spot my error...

```elixir
#!/usr/bin/env elixir 

Mix.install([
  {:mix_test_interactive, "~> 4.1"}
])

# lib/mix_test_interactive/cli.ex
defmodule MixTestInteractive.CLI do
  @moduledoc """
  Command-line interface for MixTestInteractive.
  Handles converting command line arguments into Mix.Task arguments.
  """

  def main(args) do
    # Ensure Mix is started
    Mix.start()

    # Start the application 
    Application.ensure_all_started(:mix_test_interactive)

    # Convert escript args to mix task args
    args
    |> parse_args()
    |> run()
  end

  defp parse_args(args) do
    {opts, remaining_args, _} =
      OptionParser.parse(args,
        strict: [
          stale: :boolean,
          failed: :boolean,
          watch_pattern: :string,
          timestamp_pattern: :string
        ],
        aliases: [
          p: :watch_pattern,
          ts: :timestamp_pattern
        ]
      )

    {opts, remaining_args}
  end

  defp run({opts, args}) do
    # Convert options back to string arguments
    opts_args =
      opts
      |> Enum.map(fn
        {key, true} -> "--#{key}"
        {key, value} -> "--#{key}=#{value}"
      end)

    # Combine all arguments
    all_args = opts_args ++ args

    # Run the mix task
    Mix.Task.run("test.interactive", all_args)
  end
end

MixTestInteractive.CLI.main([])
```

**Comment by randycoulman** [comment]
@andyl I just played with this a bit, and I think the following works. Give it a try and let me know if there are issues:

```elixir
#!/usr/bin/env elixir

Mix.install([
  {:mix_test_interactive, "~> 4.1"}
])

MixTestInteractive.run(System.argv())
```

I'm not sure if this is worth distributing separately (or how best to do that), but if it works for you, we can certainly add it to the docs.

**Comment by andyl** [comment]
Wow I love the simplicity.  Yes if this works IMO the best approach would be to update the docs.

My testing:
- WORKED in a project that already includes `mix_test_interactive` in the mix.exs dependencies
- FAILED in a project that does not include `mix_test_interactive` in the dependencies

To reproduce the FAILED case, first setup your script in an executable file `run_mti`:
```
> mix new testpro  # create a new mix project
> cd testpro         
> mix test         # verify that tests run  
> run_mti
** (Mix) The task "test.interactive" could not be found
```

**Comment by randycoulman** [comment]
Thanks for testing this, @andyl. I'm not getting the same results as you, so I'm curious as to what the difference is.

The simple script I posted above doesn't invoke the mix task at all, so that error message confuses me. Do you perhaps have an alias named `run_mti` that is being called instead of your script? Or perhaps a different version of that script in the path ahead of the simpler version?

In my test, I named my script `mti`, but then forgot that I have an alias with the same name, so initially I got the same error as you. But when I ran the actual script instead of my alias, all was well.

**Comment by andyl** [comment]
> In my test, I named my script mti, but then forgot that I have an alias with the same name

OMG I did exactly the same thing.  Now that this is sorted out, my FAILED case is working!

I'll test more, try to exercise all the command-line arguments.  If everything looks good, would you like me to submit a PR to update the README docs?

Thanks for finding this solution it will be a big help.
